### ISSUE TITLE
Question - Where I can find the $account?

### ISSUE THREAD

**Issue by atilacamurca** [Gingernaut/Peridot#1]
<https://github.com/Gingernaut/Peridot/blob/master/src/components/login-form.vue#L56>

Can you please tell me where is the definition of the variable `this.$account`? Is a package or some custom implementation?

Thank you.

**Comment by Gingernaut** [comment]
`$account` is a plugin I've been working on to integrate with my [user authentication micro-service](https://github.com/Gingernaut/microAuth). I've removed it from the project (forgot to remove all traces from the master branch) since I haven't gotten it 100% working but the javascript code in `$account` is in the readme of the micro-service project.

**Comment by atilacamurca** [comment]
Great! Thanks for the response.
